### ISSUE TITLE
Suggest adding support for adding, updating, deleting, multiple features at once

### ISSUE THREAD

**Issue by tomwayson** [thollingshead/arcgis-server-store#19]
The ArcGIS rest API addFeatures, updateFeatures, and deleteFeatures endpoints support multiple records by taking in arrays. The `add()`, `put()`, and `remove()` methods currently accept a single object/id and wrap it in an array before passing to the endpoints. They could check if they were passed an array, and if so, pass the array to the service endpoint .

However, they currently return a promise resolved w/ the id of the updated/deleted/added feature, I'm not sure if that is a Dojo store convention, but they'd have to probably resolve w/ an array of ids instead. This would be a breaking change.

Thoughts? Feelings?

**Comment by thollingsheadesri** [comment]
I think that the ability to add/put/remove multiple features in one request would be an extremely useful feature. I am slightly hesitant to use passing arrays to the respective methods as the means by which this can be accomplished. My concerns are based upon potentially diverging from the [Dojo Store API](https://github.com/dojo/dojo/blob/master/store/api/Store.js), and leading to issues with dgrid or observers, although I have not done any investigation to confirm this.

The Dojo Store API does provide for a `transaction()` method that returns a transaction object with `commit()` and `abort()` capability. Perhaps this is the better route? I considered implementing `transaction()` during initial development, but could not find any examples and felt the documentation was lacking on exactly how it should work.

**Comment by tomwayson** [comment]
Good points @thollingsheadesri .

What about exposing new methods like `.addFeatures()`, `.updateFeatures()`, and `.deleteFeatures()`? Since they're not part of the store API, they would not be called by grids, etc. `.add()`, `put()`, and `remove()` would in effect just become wrappers around those that would just add the argument they were passed to an array and then call the new methods with that array. The new methods would resolve with arrays of ids and the original methods would resolve with just the first (only) id. You'd probably want to move the calls to `_unflatten()` (and any other manipulation) into a loop/map w/in the new methods.

**Comment by thollingshead** [comment]
I was able to find [an example](https://github.com/SitePen/dstore/blob/d791eba222875163cfce342640d7ce6fc63f3dd2/src/db/IndexedDB.js#L150) of `transaction()` in the [dstore API](https://github.com/SitePen/dstore/blob/master/docs/Store.md). This leads me to believe `transaction()` should be used in the following manner in the Dojo Store API:

```javascript
var transaction = store.transaction();
store.add(...);
store.put(...);
store.put(...);
transaction.commit();
```

**Comment by tomwayson** [comment]
Can you use that w/ this library as is, or do you have to implement it?

If it's as is, then it's still going to make multiple atomic calls to the API instead of using [applyEdits](http://resources.arcgis.com/en/help/rest/apiref/fsedits.html).

If it has to be implemented, could it be implemented to use applyEdits?

**Comment by thollingshead** [comment]
Yes, the plan is to implement using applyEdits.

**Comment by tomwayson** [comment]
that would be sweet!
